### PR TITLE
Fei2 header

### PR DESCRIPTION
**Pull request by biohaznerd**
Added support for the new FEI2 header, which has been introduced for EPU2.9, as outlined here: https://www.fei-software-center.com/tem-apps/MRC-2014-Specifications/

### CODE REVIEW

**Comment by colinpalmer** [comment]
This looks great, thanks for the contribution! I'll merge the code anyway since it looks fine, but it'd be good to get the new dtype covered by automated tests too. Do you have an example file with the FEI2 header that you'd be happy to share publicly?

**Comment by biohaznerd** [comment]
I'm sure I can dig out an image for that. I'll take that up via e-mail with you!

**Comment by colinpalmer** [comment]
OK, that sounds good. Thanks! I'll merge this code now, so it'll be available from GitHub immediately but it'll probably take a few days for me to get a new version out on PyPI.

**Comment by biohaznerd** [comment]
Thanks :)

**Pull request merged**
